services:
  tinyurl:
    image: tinyurl
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - CONNECTION_STRING=Host=db;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    build:
      context: .
      dockerfile: TinyUrl/Dockerfile
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: []
    volumes:
      - postgres-data-prod:/var/lib/postgresql/data

volumes:
  postgres-data-prod: