networks:
  internal:
    driver: bridge
    internal: true
  public:
    driver: bridge 

services:
  tinyurl:
    image: tinyurl
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - CONNECTION_STRING=Host=db;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    build:
      context: .
      dockerfile: TinyUrl/Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - internal

  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: []
    volumes:
      - postgres-data-prod:/var/lib/postgresql/data
    networks:
      - internal

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}
    networks:
      - internal
      - public
    depends_on:
      - tinyurl

volumes:
  postgres-data-prod: