services:
  tinyurl:
    image: tinyurl
    ports:
      - "8080:8080"
    environment:
      - CONNECTION_STRING=Host=db;Database=postgres;Username=postgres;Password=postgres
    build:
      context: .
      dockerfile: TinyUrl/Dockerfile

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
        
volumes:
  postgres-data: